server:
  port: 8080

spring:
  application:
    name: auditflow-backend

  datasource:
    url: jdbc:postgresql://localhost:15432/auditflow_db
    username: auditflow_user
    password: auditflow_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  devtools:
    restart:
      enabled: true

logging:
  level:
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG